name: thema_test
description: A new Flutter module project.
publish_to: 'none'

environment:
  sdk: ">=3.6.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  thema:
    path: ../thema

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 6.0.0
