name: thema

packages:
  - ./
  - packages/**

ide:
  intellij: true


command:
  bootstrap:
    enforceLockfile: true
  clean:
    hooks:
      post: |
        melos exec -c 1 --flutter -- flutter clean

scripts:
  get:
    run: melos exec -c 1 -- flutter pub get
    description: Pub get

  outdated:
    run: melos exec -c 1 -- flutter pub outdated
    description: Check for outdated dependencies

  fmt:
    run: melos exec -c 1 -- dart format --enable-experiment=macros  .
    description: Format dart code

  fix:
    run: melos exec -c 1 -- dart fix --apply --enable-experiment=macros .
    description: Fix dart code
