name: thema

repository:
  type: github
  origin: https://github.com/ronnnnn/thema
  owner: ronnnnn
  name: thema

packages:
  - ./
  - packages/**

ide:
  intellij: true

command:
  bootstrap:
    enforceLockfile: true
  clean:
    hooks:
      post: |
        melos exec -c 1 --flutter -- flutter clean

scripts:
  prepare:
    description: Prepare for develop
    run: dart pub global activate very_good_cli 0.23.1

  get:
    description: Pub get
    run: melos exec -c 1 -- flutter pub get

  outdated:
    description: Check for outdated dependencies
    run: melos exec -c 1 -- flutter pub outdated

  fmt:
    description: Format
    run: |
      melos fix && \
      melos fmt:dart

  fmt:dry:
    description: Format (dry-run)
    run: |
      melos fix:dry && \
      melos fmt:dart:dry

  fmt:dart:
    description: Format dart
    run: melos exec -c 1 --fail-fast -- dart format --enable-experiment=macros .

  fmt:dart:dry:
    description: Format dart (dry-run)
    run: melos exec -c 1 --fail-fast -- dart format --set-exit-if-changed --enable-experiment=macros .

  fix:
    description: Fix dart
    run: melos exec -c 1 --fail-fast -- dart fix --apply --enable-experiment=macros

  fix:dry:
    description: Fix dart (dry-run)
    run: melos exec -c 1 --fail-fast -- dart fix --dry-run --enable-experiment=macros

  lint:
    description: Lint
    run: |
      melos lint:dart && \
      melos lint:flutter

  lint:dart:
    description: Lint with dart
    run: melos exec -c 1 --scope="thema" -- dart analyze --fatal-infos --fatal-warnings

  lint:flutter:
    description: Lint with flutter
    run: melos exec -c 1 --scope="thema_test" -- flutter analyze --fatal-infos --fatal-warnings

  test:
    description: Run tests
    run: melos exec -c 1 --scope="thema_test" -- flutter test --enable-experiment=macros
    packageFilters:
      dependsOn: flutter_test

  build:example:
    description: Build on thema_example
    run: |
      melos build:example:android && \
      melos build:example:ios

  build:example:android:
    description: Build android on thema_example
    run: melos exec -c 1 --scope="thema_example" -- flutter build appbundle

  build:example:ios:
    description: Build ios on thema_example
    run: melos exec -c 1 --scope="thema_example" -- flutter build ios --no-codesign
