name: Select Xcode 🔧
description: Select Xcode version for macOS

runs:
  using: 'composite'
  steps:
    - name: Extract .xcode-version
      id: version
      shell: bash
      run: |
        xcode_version=$(<.xcode-version)
        echo "xcode_version=$xcode_version" >> $GITHUB_OUTPUT

    # The path to the Xcode application is specified in the pre-installed software of GitHub Actions Runner.
    # https://github.com/actions/runner-images/tree/main/images/macos
    - name: Select Xcode version
      shell: bash
      run: |
        sudo xcode-select -s "/Applications/Xcode_${{ steps.version.outputs.xcode_version }}.app/Contents/Developer"
