name: Bug report
description: Report bug details you found and describe clearly as possible.
title: 'bug: Title of the bug'
labels: ['bug']
assignees: ['ronnnnn']
body:
  - type: textarea
    attributes:
      label: Bug overview
      description: Describe summary of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps reproduce
      description: Describe how to reproduce the bug step by step.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected result
      description: Describe expected behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual result
      description: Describe current behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Affected version
      description: Which version of thema you use.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Flutter doctor
      description: Copy and paste here, `flutter doctor -v` output.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Describe additional context if you have.
    validations:
      required: false
