name: Feature request
description: Propose adding new features or update features to existing.
title: 'feat: Title of the proposal'
labels: ['feat']
assignees: ['ronnnnn']
body:
  - type: textarea
    attributes:
      label: Feature overview
      description: Describe the feature you want to propose.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Describe additional context if you have.
    validations:
      required: false
