name: thema
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0-152

dependencies:
  flutter:
    sdk: flutter
  json: ^0.20.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
