name: thema
description: thema reduces the boilerplate code required to create ThemeExtension classes with macros.
version: 0.1.0-dev00
homepage: https://github.com/ronnnnn/thema
repository: https://github.com/ronnnnn/thema
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
funding:
  - https://github.com/sponsors/ronnnnn
topics:
  - theme
  - macros

environment:
  sdk: ">=3.6.0-0 <4.0.0"

dependencies:
  collection: ^1.18.0
  macros: ^0.1.0

dev_dependencies:
  very_good_analysis: 6.0.0
